[project]
name = "dynamics-and-relativity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan", email = "morimemento406@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "polars>=1.44.2",
    "statsmodels>=0.15.0",
    "sympy>=1.14.0",
]
[tool.uv]
config-settings = { editable_mode = "compat" }
[project.scripts]
dynamics-and-relativity = "dynamics_and_relativity:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
